const dinnerInfo = [
	{
		member_id: 1,
		member_name: 'Amit',
		house_no: 325,
		street_name: 'Max park',
		dinner_id: 'D00001001',
		dinner_date: '2020-03-15',
		venue_code: 'B01',
		venue_description: 'Grand Ball Room',
		food_code: 'C1',
		food_description: 'Curry'
	},
	{
		member_id: 2,
		member_name: 'Ben',
		house_no: 24,
		street_name: 'Hudson lane',
		dinner_id: 'D00001002',
		dinner_date: '2020-03-15',
		venue_code: 'B02',
		venue_description: 'Zoku Roof Top',
		food_code: 'S1',
		food_description: 'Soup'
	},
	{
		member_id: 2,
		member_name: 'Ben',
		house_no: 24,
		street_name: 'Hudson lane',
		dinner_id: 'D00001002',
		dinner_date: '2020-03-15',
		venue_code: 'B02',
		venue_description: 'Zoku Roof Top',
		food_code: 'C2',
		food_description: 'Cake'
	},
	{
		member_id: 3,
		member_name: 'Cristina',
		house_no: 516,
		street_name: '6th Ave',
		dinner_id: 'D00001002',
		dinner_date: '2020-03-15',
		venue_code: 'B02',
		venue_description: 'Zoku Roof Top',
		food_code: 'S1',
		food_description: 'Soup'
	},
	{
		member_id: 3,
		member_name: 'Cristina',
		house_no: 516,
		street_name: '6th Ave',
		dinner_id: 'D00001002',
		dinner_date: '2020-03-15',
		venue_code: 'B02',
		venue_description: 'Zoku Roof Top',
		food_code: 'C2',
		food_description: 'Cake'
	},
	{
		member_id: 4,
		member_name: 'Dan',
		house_no: 89,
		street_name: 'John St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'P1',
		food_description: 'Pie'
	},
	{
		member_id: 4,
		member_name: 'Dan',
		house_no: 89,
		street_name: 'John St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'T1',
		food_description: 'Tea'
	},
	{
		member_id: 4,
		member_name: 'Dan',
		house_no: 89,
		street_name: 'John St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'M1',
		food_description: 'Mousse'
	},
	{
		member_id: 5,
		member_name: 'Ema',
		house_no: 91,
		street_name: 'Pixar St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'P1',
		food_description: 'Pie'
	},
	{
		member_id: 5,
		member_name: 'Ema',
		house_no: 91,
		street_name: 'Pixar St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'T1',
		food_description: 'Tea'
	},
	{
		member_id: 5,
		member_name: 'Ema',
		house_no: 91,
		street_name: 'Pixar St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'M1',
		food_description: 'Mousse'
	},
	{
		member_id: 6,
		member_name: 'Fatime',
		house_no: 56,
		street_name: '8th Ave',
		dinner_id: 'D00001004',
		dinner_date: '2020-03-20',
		venue_code: 'B04',
		venue_description: "Mama's Kitchen",
		food_code: 'F1',
		food_description: 'Falafal'
	},
	{
		member_id: 6,
		member_name: 'Fatime',
		house_no: 56,
		street_name: '8th Ave',
		dinner_id: 'D00001004',
		dinner_date: '2020-03-20',
		venue_code: 'B04',
		venue_description: "Mama's Kitchen",
		food_code: 'M1',
		food_description: 'Mousse'
	},
	{
		member_id: 7,
		member_name: 'Gabor',
		house_no: 54,
		street_name: 'Vivaldi St',
		dinner_id: 'D00001005',
		dinner_date: '2020-03-20',
		venue_code: 'B01',
		venue_description: 'Hungry Hungary',
		food_code: 'G1',
		food_description: 'Goulash'
	},
	{
		member_id: 7,
		member_name: 'Gabor',
		house_no: 54,
		street_name: 'Vivaldi St',
		dinner_id: 'D00001005',
		dinner_date: '2020-03-20',
		venue_code: 'B05',
		venue_description: 'Hungry Hungary',
		food_code: 'P1',
		food_description: 'Pasca'
	},
	{
		member_id: 8,
		member_name: 'Hema',
		house_no: 54,
		street_name: '9 Peter St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'P1',
		food_description: 'Pie'
	},
	{
		member_id: 8,
		member_name: 'Hema',
		house_no: 54,
		street_name: '9 Peter St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'T1',
		food_description: 'Tea'
	},
	{
		member_id: 8,
		member_name: 'Hema',
		house_no: 54,
		street_name: '9 Peter St',
		dinner_id: 'D00001003',
		dinner_date: '2020-03-20',
		venue_code: 'B03',
		venue_description: 'Goat Farm',
		food_code: 'M1',
		food_description: 'Mousse'
	}
];

module.exports = dinnerInfo;
